global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "rules/*.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'benchmark-api'
    static_configs:
      - targets: ['benchmark-api:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'query-service'
    static_configs:
      - targets: ['query-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'metrics-service'
    static_configs:
      - targets: ['metrics-service:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s

  - job_name: 'trino'
    static_configs:
      - targets: ['trino:8080']
    metrics_path: '/v1/info'
    scrape_interval: 30s

  - job_name: 'presto'
    static_configs:
      - targets: ['presto:8080']
    metrics_path: '/v1/info'
    scrape_interval: 30s

  - job_name: 'starrocks'
    static_configs:
      - targets: ['starrocks-fe:8030']
    metrics_path: '/metrics'
    scrape_interval: 30s

  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s

  - job_name: 'minio'
    static_configs:
      - targets: ['minio:9000']
    metrics_path: '/minio/v2/metrics/cluster'
    scrape_interval: 30s
